name: design_system
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/voomp/icons
    - assets/stoodi/images
    - assets/voomp/icons
    - assets/stoodi/images
